services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - web
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0  # Enable external access


  web:
    build: ./backend
    ports:
      - "5000:8000"
    env_file:
      - .env.backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:17
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:


networks:
  default:
    driver: bridge