title: Chess Database Documentation
description: Documentation for the Chess Database System
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Repository settings
repository: nessaee/chess-database
github_repo: chess-database
github_username: nessaee

# Jekyll settings
baseurl: "/chess-database"
url: "https://nessaee.github.io"

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Enable search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Enable copy buttons on code blocks
enable_copy_code_button: true

# Enable anchor links
heading_anchors: true

# External navigation links
nav_external_links:
  - title: Chess Database on GitHub
    url: https://github.com/nessaee/chess-database
    hide_icon: false

# Footer content
footer_content: ""

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable Mermaid diagrams
mermaid:
  version: "10.6.1"

# Color scheme
color_scheme: light

# Aux links for upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/nessaee/chess-database"

# Makes Aux links open in new tab
aux_links_new_tab: true

# Sort order for navigation
nav_sort: case_sensitive

# Exclude from processing
exclude:
  - "*.gemspec"
  - "*.gem"
  - "Gemfile*"
  - "README.md"
  - "node_modules"
  - "*.config.js"

# Kramdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false
