# Theme settings
remote_theme: pages-themes/cayman@v0.2.0

# Site settings
title: Chess Database Documentation
description: Documentation for the Chess Database System
baseurl: "/chess-database"
url: "https://nessaee.github.io"

# Repository settings
repository: nessaee/chess-database
github_repo: chess-database
github_username: nessaee

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Search settings
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Heading anchor links
heading_anchors: true

# External navigation links
nav_external_links:
  - title: View on GitHub
    url: https://github.com/nessaee/chess-database
    hide_icon: false
    opens_in_new_tab: true

# Footer content
footer_content: ""

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Mermaid settings
mermaid:
  version: "10.6.1"
  custom: |
    {
      "theme": "neutral",
      "themeVariables": {
        "primaryColor": "#61DAFB",
        "primaryTextColor": "#333",
        "primaryBorderColor": "#333",
        "lineColor": "#333",
        "secondaryColor": "#009688",
        "tertiaryColor": "#336791"
      }
    }

# Aux links for upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/nessaee/chess-database"
aux_links_new_tab: true

# Navigation settings
nav_sort: case_sensitive
nav_external_links_new_tab: true

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red

# Exclude from processing
exclude:
  - "*.gemspec"
  - "*.gem"
  - "Gemfile*"
  - "README.md"
  - "node_modules"
  - "*.config.js"

# Kramdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false
