# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false

# Site settings
title: Chess Database Documentation
description: A powerful system for analyzing chess games and tracking player statistics
baseurl: "/chess-database"
url: "https://nessaee.github.io"
repository: nessaee/chess-database

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

# GitHub metadata settings
github: [metadata]
repository: nessaee/chess-database

# SEO settings
twitter:
  username: nessaee
  card: summary
social:
  name: Chess Database
  links:
    - https://github.com/nessaee/chess-database

# Mermaid diagram settings
mermaid:
  version: "10.6.1"
  custom: |
    {
      "theme": "neutral",
      "themeVariables": {
        "primaryColor": "#159957",
        "primaryTextColor": "#333",
        "primaryBorderColor": "#333",
        "lineColor": "#333",
        "secondaryColor": "#606c71",
        "tertiaryColor": "#159957"
      }
    }

# Search settings
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Heading anchor links
heading_anchors: true

# External navigation links
nav_external_links:
  - title: View on GitHub
    url: https://github.com/nessaee/chess-database
    hide_icon: false
    opens_in_new_tab: true

# Footer content
footer_content: ""

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links for upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/nessaee/chess-database"
aux_links_new_tab: true

# Navigation settings
nav_sort: case_sensitive
nav_external_links_new_tab: true

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red
