title: Chess Database Documentation
description: Documentation for the Chess Database system
baseurl: ""
url: ""

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/nessaee/chess-database"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_sensitive

# Footer content
footer_content: "Copyright &copy; 2024 Chess Database. Distributed under the MIT license."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Include processing
include:
  - _includes
